[package]
name = "hvm1"
version = "1.0.16"
edition = "2021"
description = "A massively parallel functional runtime."
repository = "https://github.com/HigherOrderCO/HVM1"
license = "MIT"
keywords = ["functional", "language", "runtime", "compiler", "target"]
categories = ["compilers"]

[lib]
test = true
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "hvm1"
test = false

[profile.release]
opt-level = 3

[dependencies]
HOPA = "0.1.1"
backtrace = "0.3.69"
sysinfo = "0.29.10"
clap = { version = "3.1.8", features = ["derive"] }
crossbeam = "0.8.2"
highlight_error = "0.1.1"
instant = { version = "0.1", features = [ "wasm-bindgen", "inaccurate" ] }
itertools = "0.10"
